spring.application.name=sharppay

# Server
server.port=8080

# Database — Neon PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-square-flower-alwbcpol-pooler.c-3.eu-central-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8pKVXEZqx5cW
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.hikari.connection-timeout=30000
# ===============================
# AWS CLOUD CONFIGURATION
# ===============================
aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}
aws.region=us-east-1
aws.s3.bucket-name=sharppay-kyc-images-oluwasheyi
# Resend API Key (Injected via Environment Variable)
resend.api.key=${RESEND_API_KEY}